# fly.toml app configuration file generated for echoscribe on 2025-08-14T19:48:40+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'echoscribe'
primary_region = 'lhr'

[build]
  dockerfile = 'Dockerfile'

[env]
  NODE_ENV = 'production'

[[services]]
  protocol = 'tcp'
  internal_port = 3000

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'requests'
    hard_limit = 100
    soft_limit = 50

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
